### ISSUE TITLE
App crashing on Android 7.1.2 after selecting Spotify Dogfood for notifications and granting storage permission

### ISSUE THREAD

**Issue by FedoraMaster420** [spotify-dogfood/updater-for-spotify#13]

**Comment by 2Ra66it** [comment]
Hi, try installing the latest version from here: https://github.com/spotify-dogfood/updater-for-spotify/releases/tag/1.04

**Comment by FedoraMaster420** [comment]
Hi, it still didn't work, you can see what I'm talking about from this screen capture here: https://www.dropbox.com/s/rcn8td46k3vcbtx/ScreenRecord-2018-01-28-21-28-15.mp4?dl=0
The bit at the start is just to show what I am running.

**Comment by 2Ra66it** [comment]
[UFS.zip](https://github.com/spotify-dogfood/updater-for-spotify/files/1671119/UFS.zip)
Hi again, this is a beta version of the new update, standard features should work, try...

**Comment by FedoraMaster420** [comment]
Hey, thanks this version does work without crashing however the Spotify Dogfood tab doesn't work it just says "Error something went wrong :(" at the bottom of the screen when I try to refresh

**Comment by 2Ra66it** [comment]
Hi, download a new version https://github.com/spotify-dogfood/updater-for-spotify/releases/tag/1.05
