### ISSUE TITLE
Premium features

### ISSUE THREAD

**Issue by brad2192** [spotify-dogfood/updater-for-spotify#14]
They have been disabled for the past two releases. What's the issue ? Can't select songs, it's just a stock version.

**Comment by 2Ra66it** [comment]
Hello, on the weekend I will add a full version of dogfood

**Comment by brad2192** [comment]
Sorry wrote that while I was busy at work, it looks rude lol. Anyways much appreciated! Thank you for your hard work!

**Comment by 2Ra66it** [comment]
Hi, download a new version https://github.com/spotify-dogfood/updater-for-spotify/releases/tag/1.05

**Comment by brad2192** [comment]
content://media/external/file/22386
New update same shit

**Comment by brad2192** [comment]
Screenshot didn't work, but the new version still has premium disabled. I am on a k20 plus if that helps.uninstalled all old versions previous to install

**Comment by hevatix** [comment]
Same issue

**Comment by 2Ra66it** [comment]
In the settings, click 6 times the version of the application

**Comment by hevatix** [comment]
Is not working premium features for me I have the lastes version of Spotify Dogfood.

**Comment by brad2192** [comment]
It just seems now the ads are blocked.It used to be where you can play ANY song. But now, it's pretty much Shuffle-only with no ads. Spotify Dogfood never updated us on it's changes in their modifications.

**Comment by sergiocastell** [comment]
Like you were in position to ask for any @brad2192.  
First read, then criticize. Not the opposite way.

**Comment by hevatix** [comment]
I have already read on the telegram channel how activate premium feature. Thankyou .

**Comment by brad2192** [comment]
@sergiocastell that's cute. I tried on numerous builds to do that. I remember, press it six times. Did nothing on two separate builds. Do not assume I haven't tried.

**Comment by brad2192** [comment]
On the updater it just crashes every time I try, uninstalled Spotify as well.
