### ISSUE TITLE
Updater not working properly

### ISSUE THREAD

**Issue by Rafael7up** [spotify-dogfood/updater-for-spotify#2]
Hi, I have the latest version and it tells me always to remove the original Spotify, on a new version, to download the Dogfood, but I don't have installed the original one, my mobile phone is a Nexus 5X, could you please check this issue? It happens also to a friend with S8

**Comment by 2Ra66it** [comment]
Hi, thanks for the message, I found the bug and fixed it, download and install the latest version of Updater For Spotify from here:
https://github.com/spotify-dogfood/updater-for-spotify/releases

Let me know if you find any errors :)
