### ISSUE TITLE
Download unsuccessful

### ISSUE THREAD

**Issue by flippinger** [spotify-dogfood/updater-for-spotify#5]
When I open the latest updater ([1.0.3.apk](https://github.com/spotify-dogfood/updater-for-spotify/releases/download/1.03/UpdaterForSpotify.1.0.3.apk), even though app info says it's 1.0.2), I see that an update is available:
![image](https://user-images.githubusercontent.com/3148313/33571891-b2dd5b52-d931-11e7-86b2-e4699fcf6e69.png)

However, when I click on the update button, I instantly get a "Download unsuccessful" notification.
![image](https://user-images.githubusercontent.com/3148313/33571976-eb51f16e-d931-11e7-8983-71021c26301d.png)

Storage permission is granted. No other restrictions, Honor 8 with Android 7.0 stock ROM. I already uninstalled the updater and tried the [version from readme.md](https://github.com/spotify-dogfood/updater-for-spotify/raw/master/app/release/app-release.apk), same problem; Android also shows this one as 1.0.2.

**Comment by 2Ra66it** [comment]
Hi, the fact is that on the server where to store spotify dogfood there is an error, I have already notified the creator of Spotify Dogfood and we will soon fix this problem. Updater for Spotify works correctly.

Thanks for the feedback!

**Comment by sergiocastell** [comment]
Solved
