### ISSUE TITLE
Updater shows outdated info

### ISSUE THREAD

**Issue by the4anoni** [spotify-dogfood/updater-for-spotify#6]
Reloaded it ,etc.
![screenshot_2017-12-25-21-01-07](https://user-images.githubusercontent.com/13403084/34342667-25cb9e86-e9b7-11e7-984b-57ef0b59d8e9.png)
![screenshot_2017-12-25-21-01-55](https://user-images.githubusercontent.com/13403084/34342669-2c3c8c12-e9b7-11e7-92d3-e3a532bea8d4.png)

**Comment by sergiocastell** [comment]
Solved, check it now @the4anoni. Merry Christmas!
