### ISSUE TITLE
File name interpreted as file extension

### ISSUE THREAD

**Issue by SenorKangrejos** [spotify-dogfood/updater-for-spotify#7]
Whenever I download a new .apk from updater for Spotify, the file name is something like "Spotify 8.4.32.632.apk", but my phone interprets it as a ".4.32.632.apk" file instead of an ".apk" file, and I can't install it unless I get rid of all of the periods in the filename using a file manager. 

Is there any way you could get it to replace the periods with a character like underscores to prevent issues like this? Running stock OxygenOS 5.0.1 on a OnePlus 3.

**Comment by 2Ra66it** [comment]
Those. is the filename not full? I can put a lower underscore in front of the ".apk", it's just strange that this happens

**Comment by 2Ra66it** [comment]
I published a new version fixing this error:
https://github.com/spotify-dogfood/updater-for-spotify/releases/tag/1.04
