### ISSUE TITLE
App (again..) shows outdated info

### ISSUE THREAD

**Issue by the4anoni** [spotify-dogfood/updater-for-spotify#8]
![screenshot_2018-01-12-20-42-08](https://user-images.githubusercontent.com/13403084/34892405-7a4eba80-f7d9-11e7-91a0-97bd043dc44f.png)
![screenshot_2018-01-12-20-42-00](https://user-images.githubusercontent.com/13403084/34892412-800fd81e-f7d9-11e7-9338-b1507767e027.png)
![screenshot_2018-01-12-20-42-31](https://user-images.githubusercontent.com/13403084/34892420-839dc856-f7d9-11e7-9d47-13965e831f86.png)

**Comment by sergiocastell** [comment]
This info isn't fetched automatically, and is updated MANUALLY as we can. Do not open more issues for this.

**Comment by 2Ra66it** [comment]
I updated the links
