### ISSUE TITLE
It crashes upon update

### ISSUE THREAD

**Issue by Bm5x5** [spotify-dogfood/updater-for-spotify#9]
Whenever I click to update Spotify. The whole thing crashes even when I uninstall Spotify. Fix it

**Comment by 2Ra66it** [comment]
Which version of Spotify do you have, which version of Spotify do you want to install?

Try to update the Updater for Spotify to the latest version first:
https://github.com/spotify-dogfood/updater-for-spotify/releases/tag/1.04
